### PR TITLE
rotate layer instead of view to prevent auto layout

### PR DESCRIPTION
**Pull request by nitinan59**

### CODE REVIEW

**Comment by kevincador** [comment]
Hey,

There is no need to do this with an animation with a zero duration. It produces a strange behaviour with the animation when the card snaps back in the original position.

Instead, you could do this : 

```
- (void)mdc_rotateForTranslation:(CGPoint)translation
               rotationDirection:(MDCRotationDirection)rotationDirection {
    CGFloat rotation = MDCDegreesToRadians(translation.x/100 * self.mdc_options.rotationFactor);
    self.layer.transform = CATransform3DMakeRotation(rotationDirection * rotation, 0.0, 0.0, 1.0);
}
```

**Comment by kevincador** [comment]
For this to work correctly, all the transforms should be done on the layer : 

```self.mdc_viewState.originalTransform = view.layer.transform;```

in mdc_onSwipeToChoosePanGestureRecognizer:

```self.layer.transform = self.mdc_viewState.originalTransform;```

in mdc_returnToOriginalCenter

The originalTransform property of MDCViewState should also be changed to 

```@property (nonatomic, assign) CATransform3D originalTransform;```

@nitinan59 Should I make another pull request? Or do you change yours?

**Comment by nitinan59** [comment]
@kevincador Thanks for correcting me. I will test and change mime.

**Comment by vikmeup** [comment]
This has been fixed by: https://github.com/modocache/MDCSwipeToChoose/pull/38

**Pull request closed without merging**
